// <auto-generated/>
// Generated by tools/AutomationBridgeProtocolGen from bridge_calls_spec.json
#nullable enable

using Mobsub.AutomationBridge.Protocol;
using Mobsub.AutomationBridge.Scripts.Abstractions;

namespace Mobsub.AutomationBridge.Scripts;

internal static partial class BridgeScriptCatalog
{
    private static partial IBridgeCallHandler[] CreateHandlers()
        =>
        [
            new BridgeCallHandler<BridgePingCall>(
                new BridgeMethodInfo("ping", "Health check; returns logs=['pong']."),
                HandlePing),

            new BridgeCallHandler<BridgeListMethodsCall>(
                new BridgeMethodInfo("list_methods", "List supported method names."),
                HandleListMethods),

            new BridgeCallHandler<MotionAmoApplyCall>(
                new BridgeMethodInfo("motion.amo_apply", "Aegisub-Motion Apply (ported from a-mo.Aegisub-Motion; no trim/encoding)."),
                global::Mobsub.AutomationBridge.Scripts.Motion.MotionAmoApplyHandler.Handle),

            new BridgeCallHandler<PerspectiveApplyClipQuadCall>(
                new BridgeMethodInfo("perspective.apply_clip_quad", "Insert/replace \\\\clip(m ... l ...) from AE CC Power Pin quad."),
                global::Mobsub.AutomationBridge.Scripts.Perspective.PerspectiveApplyClipQuadHandler.Handle),

            new BridgeCallHandler<PerspectiveApplyTagsFromQuadCall>(
                new BridgeMethodInfo("perspective.apply_tags_from_quad", "Insert/replace perspective tags (\\\\pos/\\\\org/\\\\frx/\\\\fry/...) from AE quad."),
                global::Mobsub.AutomationBridge.Scripts.Perspective.PerspectiveApplyTagsFromQuadHandler.Handle),

            new BridgeCallHandler<PerspectiveApplyTagsFromClipQuadCall>(
                new BridgeMethodInfo("perspective.apply_tags_from_clip_quad", "Extract quad from \\\\clip and insert perspective tags."),
                global::Mobsub.AutomationBridge.Scripts.Perspective.PerspectiveApplyTagsFromClipQuadHandler.Handle),

            new BridgeCallHandler<DrawingOptimizeLinesCall>(
                new BridgeMethodInfo("drawing.optimize_lines", "Optimize \\\\p drawings: flatten curves to m/l and optional RDP simplification."),
                global::Mobsub.AutomationBridge.Scripts.Drawing.DrawingOptimizeLinesHandler.Handle),

            new BridgeCallHandler<HydraAddTagsCall>(
                new BridgeMethodInfo("hydra.add_tags", "Add tags to the first override block (Mobsub.Hydra)."),
                global::Mobsub.AutomationBridge.Scripts.Hydra.HydraAddTagsHandler.Handle),

            new BridgeCallHandler<HydraRemoveTagsCall>(
                new BridgeMethodInfo("hydra.remove_tags", "Remove specified tags from the first/all override blocks (Mobsub.Hydra)."),
                global::Mobsub.AutomationBridge.Scripts.Hydra.HydraRemoveTagsHandler.Handle),

            new BridgeCallHandler<HydraAddTagsToTransformsCall>(
                new BridgeMethodInfo("hydra.add_tags_to_transforms", "Hydra mode 3: append tags to all existing \\\\t(...) payloads."),
                global::Mobsub.AutomationBridge.Scripts.Hydra.HydraAddTagsToTransformsHandler.Handle),

            new BridgeCallHandler<HydraSortTagsCall>(
                new BridgeMethodInfo("hydra.sort_tags", "Sort tags in override blocks using Hydra's tag order."),
                global::Mobsub.AutomationBridge.Scripts.Hydra.HydraSortTagsHandler.Handle),

            new BridgeCallHandler<HydraConvertClipCall>(
                new BridgeMethodInfo("hydra.convert_clip", "Toggle \\\\clip <-> \\\\iclip in all override blocks."),
                global::Mobsub.AutomationBridge.Scripts.Hydra.HydraConvertClipHandler.Handle),

            new BridgeCallHandler<HydraGradientCall>(
                new BridgeMethodInfo("hydra.gradient", "Hydra mode 3: gradients (vertical/horizontal/by_char/by_line)."),
                global::Mobsub.AutomationBridge.Scripts.Hydra.HydraGradientHandler.Handle),

        ];
}
