using System.Reflection;
using System.Text;

namespace AutomationBridgeProtocolGen;

internal static partial class LuaEmitterV2
{
    public static string EmitProtocolFile(BridgeCallsSpec spec, Assembly bridgeAssembly, string specFileName)
    {
        var sb = new StringBuilder(capacity: 16 * 1024);

        EmitHeader(sb, spec, specFileName);
        EmitLuaHelpers(sb);

        var packTypes = CollectPackerTypes(spec, bridgeAssembly);
        var orderedTypes = TopoSort(packTypes);
        foreach (var t in orderedTypes)
        {
            EmitTypePacker(sb, t);
            sb.AppendLine();
        }

        EmitMakeCall(sb, spec, bridgeAssembly);
        EmitMakeRequest(sb);

        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb, BridgeCallsSpec spec, string specFileName)
    {
        sb.AppendLine("-- <auto-generated/>");
        sb.Append("-- Generated by tools/AutomationBridgeProtocolGen from ").AppendLine(specFileName);
        sb.AppendLine();
        sb.AppendLine("local Gen = {}");
        sb.AppendLine();
        sb.Append("local DEFAULT_SCHEMA_VERSION = ").Append(spec.SchemaVersion).AppendLine();
        sb.AppendLine();
        sb.AppendLine("-- Bridge protocol v1 (MessagePack typed arrays + unions).");

        foreach (var call in spec.Calls)
        {
            sb.Append("local ").Append(CallConstName(call.Method)).Append(" = ").Append(call.Kind).AppendLine();
        }

        sb.AppendLine();
    }

    private static void EmitLuaHelpers(StringBuilder sb)
    {
        sb.AppendLine("local function _nil_if_empty(s)");
        sb.AppendLine("  if s == \"\" then");
        sb.AppendLine("    return nil");
        sb.AppendLine("  end");
        sb.AppendLine("  return s");
        sb.AppendLine("end");
        sb.AppendLine();

        sb.AppendLine("local function _pack_array(src, pack_elem)");
        sb.AppendLine("  if type(src) ~= \"table\" then");
        sb.AppendLine("    return nil");
        sb.AppendLine("  end");
        sb.AppendLine("  local out = {}");
        sb.AppendLine("  for i, v in ipairs(src) do");
        sb.AppendLine("    out[i] = pack_elem(v)");
        sb.AppendLine("  end");
        sb.AppendLine("  return out");
        sb.AppendLine("end");
        sb.AppendLine();

        sb.AppendLine("local function _pack_dict_str_map(src)");
        sb.AppendLine("  if type(src) ~= \"table\" then");
        sb.AppendLine("    return nil");
        sb.AppendLine("  end");
        sb.AppendLine("  local out = {}");
        sb.AppendLine("  for k, v in pairs(src) do");
        sb.AppendLine("    if type(k) == \"string\" and type(v) == \"string\" then");
        sb.AppendLine("      out[k] = v");
        sb.AppendLine("    end");
        sb.AppendLine("  end");
        sb.AppendLine("  return out");
        sb.AppendLine("end");
        sb.AppendLine();

        sb.AppendLine("local function _pack_dict_record_map(src, pack_value)");
        sb.AppendLine("  if type(src) ~= \"table\" then");
        sb.AppendLine("    return nil");
        sb.AppendLine("  end");
        sb.AppendLine("  local out = {}");
        sb.AppendLine("  for k, v in pairs(src) do");
        sb.AppendLine("    if type(k) == \"string\" and k ~= \"\" then");
        sb.AppendLine("      out[k] = pack_value(v)");
        sb.AppendLine("    end");
        sb.AppendLine("  end");
        sb.AppendLine("  return out");
        sb.AppendLine("end");
        sb.AppendLine();
    }

    private static void EmitMakeRequest(StringBuilder sb)
    {
        sb.AppendLine("-- Build a BridgeRequest (schema v1).");
        sb.AppendLine("function Gen.make_request(method, context, lines, args, schema_version)");
        sb.AppendLine("  if type(method) ~= \"string\" or method == \"\" then");
        sb.AppendLine("    error(\"mobsub_bridge_gen.make_request: method must be a non-empty string\")");
        sb.AppendLine("  end");
        sb.AppendLine();
        sb.AppendLine("  local v = tonumber(schema_version) or DEFAULT_SCHEMA_VERSION");
        sb.AppendLine("  local call = _make_call(method, context, lines, args)");
        sb.AppendLine("  return { v, call }");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("return Gen");
    }
}
