-- <auto-generated/>
-- Generated by tools/AutomationBridgeProtocolGen from bridge_calls_spec.json

local Gen = {}

local DEFAULT_SCHEMA_VERSION = 1

-- Bridge protocol v1 (MessagePack typed arrays + unions).
local CALL_PING = 0
local CALL_LIST_METHODS = 1
local CALL_MOTION_AMO_APPLY = 2
local CALL_PERSPECTIVE_APPLY_CLIP_QUAD = 3
local CALL_PERSPECTIVE_APPLY_TAGS_FROM_QUAD = 4
local CALL_PERSPECTIVE_APPLY_TAGS_FROM_CLIP_QUAD = 5
local CALL_DRAWING_OPTIMIZE_LINES = 6

local function _nil_if_empty(s)
  if s == "" then
    return nil
  end
  return s
end

local function _pack_array(src, pack_elem)
  if type(src) ~= "table" then
    return nil
  end
  local out = {}
  for i, v in ipairs(src) do
    out[i] = pack_elem(v)
  end
  return out
end

local function _pack_dict_str_map(src)
  if type(src) ~= "table" then
    return nil
  end
  local out = {}
  for k, v in pairs(src) do
    if type(k) == "string" and type(v) == "string" then
      out[k] = v
    end
  end
  if not next(out) then
    return nil
  end
  return out
end

local function _pack_dict_record_map(src, pack_value)
  if type(src) ~= "table" then
    return nil
  end
  local out = {}
  for k, v in pairs(src) do
    if type(k) == "string" and k ~= "" then
      out[k] = pack_value(v)
    end
  end
  if not next(out) then
    return nil
  end
  return out
end

local function _pack_StyleInfo(t)
  if type(t) ~= "table" then
    return { 7, 0, 0, 0, 100, 100, 0, 0, 0 }
  end
  local out = {}
  out[1] = tonumber(t.align) or 7
  out[2] = tonumber(t.margin_l) or 0
  out[3] = tonumber(t.margin_r) or 0
  out[4] = tonumber(t.margin_t) or 0
  out[5] = tonumber(t.scale_x) or 100
  out[6] = tonumber(t.scale_y) or tonumber(t.scale_x) or 100
  out[7] = tonumber(t.outline) or 0
  out[8] = tonumber(t.shadow) or 0
  out[9] = tonumber(t.angle) or 0
  return out
end

local function _pack_BridgeAmoClipOptions(t)
  if type(t) ~= "table" then
    return { true, true, true, false, true, true, false, 1 }
  end
  local out = {}
  out[1] = t.x_position ~= false
  out[2] = t.y_position ~= false
  out[3] = t.x_scale ~= false
  out[4] = t.z_rotation and true or false
  out[5] = t.rect_clip ~= false
  out[6] = t.vect_clip ~= false
  out[7] = t.rc_to_vc and true or false
  out[8] = tonumber(t.start_frame) or 1
  return out
end

local function _pack_BridgeAmoFixOptions(t)
  if type(t) ~= "table" then
    return { false, true, true, 0.2, 2 }
  end
  local out = {}
  out[1] = t.enabled and true or false
  out[2] = t.apply_main ~= false
  out[3] = t.apply_clip ~= false
  out[4] = tonumber(t.diff) or 0.2
  out[5] = tonumber(t.round_decimals) or 2
  return out
end

local function _pack_BridgeAmoMainOptions(t)
  if type(t) ~= "table" then
    return { true, true, false, false, true, true, true, true, 1, false, nil, false, true, true, false, true, true, 1, 2, 0, 0 }
  end
  local out = {}
  out[1] = t.x_position ~= false
  out[2] = t.y_position ~= false
  out[3] = t.origin and true or false
  out[4] = t.abs_pos and true or false
  out[5] = t.x_scale ~= false
  out[6] = t.border ~= false
  out[7] = t.shadow ~= false
  out[8] = t.blur ~= false
  out[9] = tonumber(t.blur_scale) or 1
  out[10] = t.z_rotation and true or false
  out[12] = t.clip_only and true or false
  out[13] = t.rect_clip ~= false
  out[14] = t.vect_clip ~= false
  out[15] = t.rc_to_vc and true or false
  out[16] = t.kill_trans ~= false
  out[17] = t.relative ~= false
  out[18] = tonumber(t.start_frame) or 1
  out[19] = tonumber(t.linear_mode) or 2
  out[20] = tonumber(t.segment_pos_eps) or 0
  out[21] = tonumber(t.pos_error_mode) or 0
  return out
end

local function _pack_BridgeScriptResolution(t)
  if type(t) ~= "table" then
    return nil
  end
  local w = tonumber(t.w)
  if w == nil then
    return nil
  end
  if w < 1 then
    return nil
  end
  local h = tonumber(t.h)
  if h == nil then
    return nil
  end
  if h < 1 then
    return nil
  end
  return { w, h }
end

local function _pack_BridgeContext(t)
  if type(t) ~= "table" then
    return { nil }
  end
  local out = {}
  out[1] = (type(t.script_resolution) == "table") and _pack_BridgeScriptResolution(t.script_resolution) or nil
  return out
end

local function _pack_BridgeLine(t)
  if type(t) ~= "table" then
    return nil
  end
  local out = {}
  out[1] = tonumber(t.index) or 0
  out[2] = tostring(t.class or "")
  out[3] = (((type(t.text_utf8) == "string") and t.text_utf8) or ((type(t.text) == "string") and t.text) or "")
  out[4] = t.raw
  out[5] = t.start_time
  out[6] = t.end_time
  out[7] = t.start_frame
  out[8] = t.end_frame
  out[9] = t.layer
  out[10] = t.comment
  out[11] = t.style
  out[12] = t.actor
  out[13] = t.effect
  out[14] = t.margin_l
  out[15] = t.margin_r
  out[16] = t.margin_t
  out[17] = _pack_dict_str_map(t.extra)
  out[18] = t.width
  out[19] = t.height
  out[20] = t.align
  return out
end

local function _pack_DrawingOptimizeLinesArgs(t)
  if type(t) ~= "table" then
    return { 0.25, 0.1, 0 }
  end
  local out = {}
  out[1] = tonumber(t.curve_tolerance) or 0.25
  out[2] = tonumber(t.simplify_tolerance) or 0.1
  out[3] = tonumber(t.precision_decimals) or 0
  return out
end

local function _pack_MotionAmoApplyArgs(t)
  if type(t) ~= "table" then
    return { 0, 0, {}, "", nil, nil, _pack_BridgeAmoFixOptions(nil), _pack_BridgeAmoMainOptions(nil), _pack_BridgeAmoClipOptions(nil) }
  end
  local out = {}
  out[1] = tonumber(t.selection_start_frame) or 0
  out[2] = tonumber(t.total_frames) or 0
  out[3] = t.frame_ms or {}
  out[4] = (((type(t.main_data) == "string") and t.main_data) or ((type(t.main_data_utf8) == "string") and t.main_data_utf8) or "")
  out[5] = _nil_if_empty((((type(t.clip_data) == "string") and t.clip_data) or ((type(t.clip_data_utf8) == "string") and t.clip_data_utf8) or nil))
  out[6] = _pack_dict_record_map(t.styles, _pack_StyleInfo)
  out[7] = _pack_BridgeAmoFixOptions(t.fix)
  out[8] = _pack_BridgeAmoMainOptions(t.main)
  out[9] = _pack_BridgeAmoClipOptions(t.clip)
  return out
end

local function _pack_PerspectiveApplyClipQuadArgs(t)
  if type(t) ~= "table" then
    return { "", nil, nil }
  end
  local out = {}
  out[1] = tostring(t.ae_text or "")
  out[2] = t.effect_group
  out[3] = t.frame
  return out
end

local function _pack_PerspectiveApplyTagsFromClipQuadArgs(t)
  if type(t) ~= "table" then
    return { nil, nil, nil, 2, 1, 3, 0, 0 }
  end
  local out = {}
  out[1] = t.width
  out[2] = t.height
  out[3] = t.align
  out[4] = tonumber(t.org_mode) or 2
  out[5] = tonumber(t.layout_scale) or 1
  out[6] = tonumber(t.precision_decimals) or 3
  out[7] = tonumber(t.origin_x) or 0
  out[8] = tonumber(t.origin_y) or 0
  return out
end

local function _pack_PerspectiveApplyTagsFromQuadArgs(t)
  if type(t) ~= "table" then
    return { "", nil, nil, nil, nil, nil, 2, 1, 3, 0, 0 }
  end
  local out = {}
  out[1] = tostring(t.ae_text or "")
  out[2] = t.effect_group
  out[3] = t.frame
  out[4] = t.width
  out[5] = t.height
  out[6] = t.align
  out[7] = tonumber(t.org_mode) or 2
  out[8] = tonumber(t.layout_scale) or 1
  out[9] = tonumber(t.precision_decimals) or 3
  out[10] = tonumber(t.origin_x) or 0
  out[11] = tonumber(t.origin_y) or 0
  return out
end

local function _make_call(method, context, lines, args)
  if method == "ping" then
    return { CALL_PING, {} }
  end
  if method == "list_methods" then
    return { CALL_LIST_METHODS, {} }
  end
  if method == "motion.amo_apply" then
    return { CALL_MOTION_AMO_APPLY, { _pack_BridgeContext(context), _pack_array(lines, _pack_BridgeLine), _pack_MotionAmoApplyArgs(args) } }
  end
  if method == "perspective.apply_clip_quad" then
    return { CALL_PERSPECTIVE_APPLY_CLIP_QUAD, { _pack_BridgeContext(context), _pack_array(lines, _pack_BridgeLine), _pack_PerspectiveApplyClipQuadArgs(args) } }
  end
  if method == "perspective.apply_tags_from_quad" then
    return { CALL_PERSPECTIVE_APPLY_TAGS_FROM_QUAD, { _pack_BridgeContext(context), _pack_array(lines, _pack_BridgeLine), _pack_PerspectiveApplyTagsFromQuadArgs(args) } }
  end
  if method == "perspective.apply_tags_from_clip_quad" then
    return { CALL_PERSPECTIVE_APPLY_TAGS_FROM_CLIP_QUAD, { _pack_array(lines, _pack_BridgeLine), _pack_PerspectiveApplyTagsFromClipQuadArgs(args) } }
  end
  if method == "drawing.optimize_lines" then
    return { CALL_DRAWING_OPTIMIZE_LINES, { _pack_array(lines, _pack_BridgeLine), _pack_DrawingOptimizeLinesArgs(args) } }
  end
  error("mobsub: unsupported method: " .. tostring(method))
end

-- Build a BridgeRequest (schema v1).
function Gen.make_request(method, context, lines, args, schema_version)
  if type(method) ~= "string" or method == "" then
    error("mobsub_bridge_gen.make_request: method must be a non-empty string")
  end

  local v = tonumber(schema_version) or DEFAULT_SCHEMA_VERSION
  local call = _make_call(method, context, lines, args)
  return { v, call }
end

return Gen
